-- MySQL Script generated by MySQL Workbench
-- Dom 06 Ago 2017 16:51:47 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineerin

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
	CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
	USE `mydb` ;

	-- -----------------------------------------------------
	-- Table `mydb`.`institutions`
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `mydb`.`institutions` (
	  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	  `nome` VARCHAR(80) NOT NULL,
	  `cnpj` CHAR(14) NOT NULL,
	  `rua` VARCHAR(45) NOT NULL,
	  `numero` VARCHAR(45) NOT NULL,
	  `bairro` VARCHAR(45) NOT NULL,
	  `cidade` VARCHAR(45) NOT NULL,
	  `complemento` VARCHAR(45) NOT NULL,
	  `created` DATETIME NULL,
	  `modified` DATETIME NULL,
	  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefone` CHAR(11) NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45)NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `institutions_id` INT UNSIGNED NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`institutions_id`) REFERENCES `mydb`.`institutions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`roles_id`)REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `evento` VARCHAR(80) NOT NULL,
  `norma` VARCHAR(80) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `resumo` VARCHAR(1000) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`);


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(250) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `groups_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`groups_id`)
    REFERENCES `mydb`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`criterions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`criterions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evaluations_id` INT NOT NULL,
  PRIMARY KEY (`id`, `evaluations_id`),
    FOREIGN KEY (`evaluations_id`)
    REFERENCES `mydb`.`evaluations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table `mydb`.`subcriterions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcriterions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nota` FLOAT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `criterions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `criterions_id`),
    FOREIGN KEY (`criterions_id`)
    REFERENCES `mydb`.`criterions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table `mydb`.`users_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_projects` (
  `users_id` INT UNSIGNED NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_groups` (
  `user_id` INT UNSIGNED NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_usuarios_has_grupos_grupos1_idx` (`group_id` ASC),
  INDEX `fk_usuarios_has_grupos_usuarios1_idx` (`user_id` ASC),
  CONSTRAINT `fk_usuarios_has_grupos_usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_grupos_grupos1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
